### ISSUE TITLE
Installation - ERROR: Process exited with code 25

### ISSUE THREAD

**Issue by cocoon77** [iobroker-community-adapters/ioBroker.mikrotik#1]
I tried to install the adapter and get this error:

NPM version: 6.14.15
npm install iobroker.mikrotik@1.0.16 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code E404
npm ERR! 404 Not Found - GET https://codeload.github.com/homeinstalator/mikronode-ng/tar.gz/v1.0.11npm ERR! 404 npm ERR! 404 'mikronode-ng@https://github.com/homeinstalator/mikronode-ng/archive/v1.0.11.tar.gz' is not in the npm registry.npm ERR! 404 You should bug the author to publish it (or use the name yourself!)npm ERR! 404 It was specified as a dependency of 'iobroker.mikrotik'npm ERR! 404 npm ERR! 404 Note that you can also install from anpm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2021-11-24T14_31_56_189Z-debug.log
host.SmartHomeBck Cannot install iobroker.mikrotik@1.0.16: 1
ERROR: Process exited with code 25

Log:

21 verbose stack Error: 404 Not Found - GET https://codeload.github.com/homeinstalator/mikronode-ng/tar.gz/v1.0.11
22 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:117:15
22 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
23 verbose statusCode 404
24 verbose pkgid mikronode-ng@https://github.com/homeinstalator/mikronode-ng/archive/v1.0.11.tar.gz
25 verbose cwd /opt/iobroker
26 verbose Linux 5.10.63-v7l+
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.mikrotik@1.0.16" "--loglevel" "error" "--prefix" "/opt/iobroker"
28 verbose node v14.18.1
29 verbose npm  v6.14.15
30 error code E404
31 error 404 Not Found - GET https://codeload.github.com/homeinstalator/mikronode-ng/tar.gz/v1.0.11
32 error 404
```

**Comment by TimoS911** [comment]
Same Error here. Seems like mikronode-ng link is not working anymore.
Any alternative to get this adapter working?

**Comment by Apollon77** [comment]
Is the GitHub version here working?

**Comment by cocoon77** [comment]
> Is the GitHub version here working?

I have a running Version 1.0.16, but a new installation does not work ...

**Comment by TimoS911** [comment]
Installation via "install from github" at the adapter window doesnt work.
Is there any way to get the dependency that seems missing?
Another instance on a different iObroker is still running since month but a new installation is not possible.

**Comment by jhedtmann** [comment]
Looks like the project has been abandoned by the original author. What are the steps necessary to install from an cloned git repo?

**Comment by cocoon77** [comment]
I hope this helps

[mikronode-ng.zip](https://github.com/iobroker-community-adapters/ioBroker.mikrotik/files/8922255/mikronode-ng.zip)

**Comment by luftdieb** [comment]
Problem with installation still exist. Also no success with provided mikronode-ng.zip by using local webserver.
Is there any description available, how to install with current version of ioBroker ?

**Comment by mcm1957** [comment]
looks like this is outdated
