### ISSUE TITLE
 mikrotik.0.commands.add_firewall - Default value has to be type "string" but received type "boolean"

### ISSUE THREAD

**Issue by cocoon77** [iobroker-community-adapters/ioBroker.mikrotik#138]
**Versions:**  
 - Adapter version: v1.2.0
 - JS-Controller version: 6.0.8
 - Node version: v20.15.1
 - Operating system: Raspberry Pi OS

I found this in my logs:
Object mikrotik.0.commands.add_firewall is invalid: Default value has to be type "string" but received type "boolean"

It looks like that this don't has any negative effect but maybe you can fix it.

Regards
Martin

**Comment by mcm1957** [comment]
@cocoon77 

fixed with 1.2.1 (available at latests tomorrow) - please verify.

**Comment by cocoon77** [comment]
no more errors so far, thx
